name: Build images
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5' # Run every friday at midnight

env:
  KERNEL_BRANCH: 6.12.1

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Substitute placeholders in configs
        run: |
          find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Install pmbootstrap from git
        run: |
          git clone --branch jambokill-3.3.2-patch-bc88 --depth 1 https://gitlab.postmarketos.org/jambokill/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Set up pmaports
        run: |
          echo -e '\n\n' | pmbootstrap init || true
          cd ~/.local/var/pmbootstrap/cache_git/pmaports
          git remote add postmarketos https://gitlab.postmarketos.org/postmarketOS/pmaports.git
          git fetch postmarketos v25.06
          git reset --hard postmarketos/v25.06
          git remote add github https://github.com/jambokill/pmaports.git
          git fetch github nikroks/alioth
          git checkout github/nikroks/alioth -- device/testing/device-xiaomi-alioth/
          git checkout github/nikroks/alioth -- device/testing/firmware-xiaomi-alioth/
          git checkout github/nikroks/alioth -- device/testing/linux-postmarketos-qcom-sm8250-alioth/
          git status

      - name: Clone kernel sources
        run: |
          git clone https://github.com/mainlining/linux.git --single-branch --branch nikroks/alioth --depth 1 ./linux

      - name: Choose any SM8250 device in pmbootstrap to build kernel
        run: |
          cp xiaomi-alioth.cfg ~/.config/pmbootstrap_v3.cfg

      - name: Compile kernel with envkernel
        run: |
          cd linux
          shopt -s expand_aliases
          source ../pmbootstrap/helpers/envkernel.sh
          make defconfig sm8250.config
          make -j$(nproc)
          pmbootstrap --verbose build --envkernel linux-postmarketos-qcom-sm8250-alioth
          
      - name: Create artifact directory
        run: |
          mkdir out

      - name: Build xiaomi-alioth
        run: |
          cp xiaomi-alioth.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap install --password 147147
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-tianma-alioth.img
          cp /tmp/postmarketOS-export/xiaomi-alioth.img out/rootfs-xiaomi-alioth.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-alioth
          path: out/*-alioth.img*
          retention-days: 7
